---
title: "Untitled"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

train_names <- read.csv("TrainNames.csv", stringsAsFactors = FALSE)

get_mrt_station_coordinates <- function(station_names) {
  coordinates_list <- lapply(station_names, function(name) {
    coords <- getCoordinatesFromAddress(name)
    return(list(name = name, coordinates = coords))
  })
  
  return(coordinates_list)
}

mrt_station_coordinates <- get_mrt_station_coordinates(train_names$mrt_station_english)

mrt_station_coordinates[[1]]$name
mrt_station_coordinates[[1]]$coordinates



traffic_density <- getMrtPlatformDensity("NSL")
traffic_density




## Rainfall Bar Graph (To be used) 

# read the CSV file
rainfall <- read.csv("MonthlyRainfall.csv")

# convert month to date format
rainfall$month <- as.Date(paste(rainfall$month, "-01", sep = ""), format = "%Y-%m-%d")

# filter the data for time period from 2013 to 2022
rainfall <- rainfall[format(rainfall$month, "%Y") >= "2013" & format(rainfall$month, "%Y") <= "2022", ]

# calculate average number of rainy days for each month
monthly_avg <- aggregate(no_of_rainy_days ~ format(month, "%b"), data = rainfall, FUN = mean)

# rename the column names
colnames(monthly_avg) <- c("Month", "Average Rainy Days")

# plot the monthly averages
ggplot(monthly_avg, aes(x = Month, y = `Average Rainy Days`, fill = `Average Rainy Days`)) + 
  geom_bar(stat = "identity") +
  scale_fill_gradient(low = "blue", high = "red") +
  ggtitle("Average Monthly Rainy Days from 2013 to 2022") +
  ylab("Average Number of Rainy Days") +
  xlab("Month") +
  theme_classic() +
  scale_y_continuous(expand = c(0, 0)) +
  scale_x_discrete(limits = month.abb)




